package controllers;

import javafx.fxml.FXML;

import javafx.scene.control.TextField;

import javafx.event.ActionEvent;

public class LoginController {
	@FXML
	private TextField username;
	@FXML
	private TextField password;

	// Event Listener on Button.onAction
	@FXML
	public void login(ActionEvent event) {
		// TODO Autogenerated
	}
}
