package controllers;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;
import javafx.stage.Stage;
import javafx.event.ActionEvent;

import javafx.scene.control.Label;

import javafx.scene.control.ComboBox;

public class UserController extends ControllerHelper{
	@FXML
	private Button logout;
	@FXML
	private TextField username;
	@FXML
	private Button back;
	@FXML
	private Button submit;
	@FXML
	private ComboBox privilege;
	@FXML
	private Label currentFirstName;
	@FXML
	private TextField firstName;
	@FXML
	private TextField lastName;
	@FXML
	private TextField email;

	// Event Listener on Button[#logout].onAction
	@FXML
	public void logout() {
		super.logout(logout);
	}
	// Event Listener on Button[#back].onAction
	@FXML
	public void backToUserView(ActionEvent event) {
		Stage stage = (Stage) back.getScene().getWindow();
		String view = "/views/UserListView.fxml";
		changeScene(stage,view);
	}
	// Event Listener on Button[#submit].onAction
	@FXML
	public void createUser(ActionEvent event) {
		// TODO Autogenerated
	}
}
