package controllers;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;
import javafx.scene.text.Text;
import objects.Users;
import javafx.event.ActionEvent;

import javafx.scene.control.Label;

import javafx.scene.control.ComboBox;

public class UserController {
	@FXML
	private Button logout;
	@FXML
	private TextField username;
	@FXML
	private Button back;
	@FXML
	private Button submit;
	@FXML
	private ComboBox privilege;
	@FXML
	private Label currentFirstName;
	@FXML
	private TextField firstName;
	@FXML
	private TextField lastName;
	@FXML
	private TextField email;
	@FXML
	private TextField password;
	@FXML
	private Label privLabel;
	@FXML
	private Text passLabel;
	
	public void initialize(){
		Users currentUser = LoginController.currentUser;
		Users selectedUser = UserListController.selectedUser;
		if(currentUser ==null){
			//new user
			privLabel.setVisible(false);
			privilege.setVisible(false);
			submit.setText("Create");
			
		}else{
			submit.setText("Update");
			passLabel.setVisible(false);
			password.setVisible(false);
			username.setText(selectedUser.getUsername());
			firstName.setText(selectedUser.getFirstName());
			lastName.setText(selectedUser.getLastName());
			privilege.setValue(selectedUser.getPrivilege());
			email.setText(selectedUser.getEmail());
			
			
			
		}
		
	}
	// Event Listener on Button[#logout].onAction
	@FXML
	public void logout(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#back].onAction
	@FXML
	public void backToUserView(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#submit].onAction
	@FXML
	public void createUser(ActionEvent event) {
		// TODO Autogenerated
	}
}
